[auth_users]

# 이성욱
[auth_users.piere]
email = "piere@poscoenc.com"
name = "이성욱"
password = "LD0078"
role = "admin"
permissions = ["all"]

# 김민수
[auth_users.user1]
email = "kim.minsoo@example.com"
name = "김민수"
password = "YU2790"
role = "user"
permissions = ["번역하기", "파일 보관함"]

# 이지은
[auth_users.user2]
email = "lee.jieun@example.com"
name = "이지은"
password = "XM7357"
role = "user"
permissions = ["검색 & AI 채팅", "도면/스펙 분석"]

# 박준호
[auth_users.user3]
email = "park.junho@example.com"
name = "박준호"
password = "RO7971"
role = "user"
permissions = ["엑셀데이터 자동추출", "사진대지 자동작성"]

# 최유나
[auth_users.user4]
email = "choi.yuna@example.com"
name = "최유나"
password = "NA2284"
role = "user"
permissions = ["작업계획 및 투입비 자동작성", "번역하기"]

# 정우성
[auth_users.user5]
email = "jung.woosung@example.com"
name = "정우성"
password = "OX1684"
role = "user"
permissions = ["파일 보관함", "검색 & AI 채팅", "도면/스펙 분석"]

