[auth_users]

# 이성욱
[auth_users.piere]
email = "piere@poscoenc.com"
name = "이성욱"
password = "ER2312"
role = "admin"
permissions = ["all"]

# 고은경
[auth_users.user1]
email = "kobari@poscoenc.com"
name = "고은경"
password = "NU1763"
role = "user"
permissions = ["번역하기", "파일 보관함"]

# 이지은
[auth_users.user2]
email = "lee.jieun@example.com"
name = "이지은"
password = "VX8661"
role = "user"
permissions = ["검색 & AI 채팅", "도면/스펙 분석"]

# 박준호
[auth_users.user3]
email = "park.junho@example.com"
name = "박준호"
password = "PF4413"
role = "user"
permissions = ["엑셀데이터 자동추출", "사진대지 자동작성"]

# 최유나
[auth_users.user4]
email = "choi.yuna@example.com"
name = "최유나"
password = "DT5081"
role = "user"
permissions = ["작업계획 및 투입비 자동작성", "번역하기"]

# 정우성
[auth_users.user5]
email = "jung.woosung@example.com"
name = "정우성"
password = "VT2871"
role = "user"
permissions = ["파일 보관함", "검색 & AI 채팅", "도면/스펙 분석"]

# 이근배
[auth_users.r9t]
email = "r9t@poscoenc.com"
name = "이근배"
password = "RL4971"
role = "user"
permissions = ["검색 & AI 채팅", "도면/스펙 분석", "파일 보관함"]

