# Streamlit secrets.toml (Sheets + Gemini)

TIMEZONE = "Asia/Seoul"
GEMINI_API_KEY = "여기에_당신의_Gemini_API_Key"

[firestore]
collection = "measurements"   # 기본 저장 컬렉션명(원하면 변경)

[gcp_service_account]
type = "service_account"
project_id = "temperature-471604"
private_key_id = "8ab815d8646b17d8234cb10ece47a03a36367aad"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkW34WYr+zStqz
hJMl3h8f8yxSkLNX3EwhTlczH5shDdRqr5Ag19r/wPShxVSWaKyFhD81ZCC8MkOO
xoYfYcdtCU8bdHZw/lIODjE054yF3sB+1FpHC1S8kS+LtJpiytIiF1tXYdYg+u8b
ZzS2csWWWenz/ulGnJdaJsX+ktr4/cRXS3Djfr9KTW8ca80IGPU+Hy7Nd3SvSDCw
Z54lRMY5AFRr10T7vwGkSn1iJOHpoHrUEof/hn380g/MX2cldZ4zSoj8MYtYb7lb
T+wkT/dIAmCBwYp7j539QoBxaZfUGGjSvW41ZbPZGlgoxYIweG63zb/51ZGrV7nV
tNHZ0fKtAgMBAAECggEADqNrdnjzE/ftxKFhLbU71m+lGfFzV7byPOEqWQ5OlcIS
kjHyx0oSYkcAQsw9fWvzOa0OqCWz2K8tXzEFTxQ5W9fBaPOVfPjZvBC9hzW8SUwO
nv0w0TUMJgNUVcAPJA9maczkwMKg/Kz80Nb/VeSg/oQhly6z/isCO/BKICNaR2TG
HKNC9icmxePb7Uatc3AGxjLiiKL7RW8Ag2rElh2QgZ9IpPZR7zdzYvRpQP6SGGC1
9F/ZM4TrRINOk2MVV4NgiT8x0UKMH0lhl5csdjmnccI8hQO/XBDwsaV7k3UekmP+
wMCfTkrnjxW3t3MkgnOgOlLrjco7XhA9XxhQHz88LQKBgQDXBIxK6b3xkEUWzv4R
D7VSmbIB9luezc6k5Si4MCUrQqbzVKnxVJOUOmH6uZ744Qi1fSuTfkrIirqVgmcf
PPr3ibAk9wF07H3htYET7Xo8Ybc1eC0JZelXoMa7BDeuX3mjkJ2nJmNVrIWQN2Q+
TEDCRnOTd7qApJC9FPI6LqtsnwKBgQDDrw07wUJGr4XUxBUQp8HKGtCGjRjx404K
ho0vVlmwqfUbm8ME53LjxOEAYb5lSTRUceIxc5aMYCDnPvn1mqSqO0SOt9mVIpd/
+ftm9Hjw07Y2sVNm/0TJ6PQQeG+eeseCKpmGdZWP9B+lBkM5YiDWas+WZP5J5cTz
ZYFSb5NRMwKBgQC8GgF1g9ikXDbkxj6jxF83HLgKWXA7lAZkYQlnYM8TcmLFWtq1
Ae19bjnK8totFgjdZNxbUs+vcxXZt9PpExrmtPCA1gnTNRTHAVcjjMwzyLRTNYgI
wbwJ6eAROZZQmLu8KMaStNWP3LaXvK2YhnLcwm9XohVpdw4cLBfgaHWVNwKBgQCg
ExPlPNuljTIScfC1djXdyX+pgcTVIteVXqoh/iZSkUWTtyCaY2clkclpkYu5uV+Y
cKzTPTX7USu5X1gEpONs6hzUDutrxyddpjYU64n/n4CgTwDl8Y3pCaqVyp+sac3I
2mZKiue1IcO9MFlPmMk5/Zgg9C7cbpxlazSWJfXB5wKBgB7IE6gH1HT9rjaG876G
MsF1a8VVFAR6dNzgzKtNAR3u7tGBi05U6D7iLzGRXjW7pWkwvGDOFHmVz39Kn795
M4YHoS8aWIzcu5/8Ly8GL2LS143Z8qRdvE0dyaojKbW+XIc70rW9euTppqlEKYVo
eaNmOckq9pa6SBg48ew/pSuK
-----END PRIVATE KEY-----"""
client_email = "temperature-app-writer@temperature-471604.iam.gserviceaccount.com"
client_id = "103997659958450494668"
token_uri = "https://oauth2.googleapis.com/token"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/temperature-app-writer%40temperature-471604.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
